### ISSUE TITLE
Step 2b

### ISSUE THREAD

**Issue by theRealBitcoinClub** [blockparty-sh/mist-miner#1]
![Screenshot_2020-06-25_19-58-27](https://user-images.githubusercontent.com/35400618/85807191-27ee0180-b71f-11ea-88ac-15e4545e7395.png)

Would like to make you aware that I followed the instructions, the 2nd worked but on the 3rd this came up, maybe for completeness you might want to add that, I followed the screen and will continue with 3rd afterwards.

**Comment by blockparty-sh** [comment]
You are on ubuntu? Yeah these are mac instructions.. would be cool if different sections for Mac, Windows, Linux

**Comment by theRealBitcoinClub** [comment]
Yes I am on ubuntu!

Oh its mac instructions, they worked quite well until I ran into an issue on npm install.
