### ISSUE TITLE
Installing mist

### ISSUE THREAD

**Issue by theRealBitcoinClub** [blockparty-sh/mist-miner#2]
[npm-debug.log](https://github.com/blockparty-sh/mist-miner/files/4839355/npm-debug.log)

I reached step 6, then it failed on npm install after a while.

Then I skipped step 7 to test step 8, npm start also threw an error.

Maybe that log file gives you a hint?

It includes the same output as I had on my console.

Thanks

**Comment by ianGre** [comment]
You have this in the log. `25 error Make sure you have the latest version of node.js and npm installed.`

I had to do some updates like this when I followed the instructions based on some errors I got, but I didn't proceed in the steps until each was completed.

**Comment by theRealBitcoinClub** [comment]
Thanks

Currently updating node

Ill keep you updated

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by theRealBitcoinClub** [comment]
I did update NPM

Still getting that same error

It says there is some argument missing when I execute

npm install

Within the miners folder

Enviado desde ProtonMail móvil

-------- Mensaje original --------

**Comment by theRealBitcoinClub** [comment]
![Screenshot_2020-06-30_19-09-04](https://user-images.githubusercontent.com/35400618/86185802-42e8b900-bb05-11ea-8a56-25ed30f39cbd.png)
[2020-06-30T08_42_38_374Z-debug.log](https://github.com/blockparty-sh/mist-miner/files/4854791/2020-06-30T08_42_38_374Z-debug.log)
[2020-06-30T23_08_18_005Z-debug.log](https://github.com/blockparty-sh/mist-miner/files/4854792/2020-06-30T23_08_18_005Z-debug.log)

**npm install seems to have completed successfully?

npm start throws the error**

I have the compressed WIF from memo.cash inside the example.env file

I tried the uncompressed and compressed base58 WIF both with same results

**Comment by theRealBitcoinClub** [comment]
So the issue was that I was editing inside example.env but not inside .env :)

Now I am at step 9 and shall fund the wallet.

**Is it possible to fund my wallet with memo.cash tools using their address?**

**Comment by theRealBitcoinClub** [comment]
ok i did a git pull & then it worked thanks for the support
